name: CICD

on:
  push:
    branches:
      - "feature/**"
      - "develop"
      - "main"

jobs:
  quality:
    name: Run Pester and PSSA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PSScriptanalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning -ErrorAction Stop

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path "./XlsCoordinatesConverter-wts" -Passthru

  build:
    name: Build Module
    needs: quality
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/head/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Logic
        shell: pwsh
        run: |
          Invoke-Build Build
      - name: Archive module files
        shell: pwsh
        run: |
          Compress-Archive -Path '.\*' -DestinationPath "Module.zip" -Force
      - name: Upload module artifact
        uses: actions/upload-artifact@v4
        with:
          name: module-archive
          path: Module.zip

  publish:
    name: Publish to Gallery
    needs: build
    if: github.ref == 'refs/head/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to PowerShell Gallery
        shell: pwsh
        env:
          POWERSHELL_GALLERY_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
        run: |
          Publish-Module -Path '.' -NuGetApiKey $env:POWERSHELL_GALLERY_API_KEY -Confirm:$false
